pub struct Book {
    pub contents: Vec<BookContents>,
}

pub enum BookContents {
    Id {
        code: BookIdentifier,
        text: String,
    },
    Usfm(String),
    Encoding(BookEncoding),
    Status(u16),
    Chapter(u16),
    AltChapter(u16),
    Paragraph {
        style: ParagraphStyle,
        contents: Vec<ParagraphContents>,
    },
    Poetry {
        style: PoetryStyle,
        contents: Vec<ParagraphContents>,
    },
    Element {
        ty: ElementType,
        contents: Vec<ElementContents>,
    },
}

pub enum ParagraphContents {
    Verse(u16),
    Line(String),
    Character {
        ty: CharacterType,
        contents: Vec<CharacterContents>,
    },
    Footnote {
        style: FootnoteStyle,
        elements: Vec<FootnoteElement>,
    },
    CrossRef {
        elements: Vec<CrossRefElement>,
    },
}

pub enum ElementContents {
    Line(String),
    Character {
        ty: CharacterType,
        contents: Vec<CharacterContents>,
    },
    Footnote {
        style: FootnoteStyle,
        elements: Vec<FootnoteElement>,
    },
    CrossRef {
        elements: Vec<CrossRefElement>,
    },
}

pub enum CharacterContents {
    Line(String),
    Character {
        ty: CharacterType,
        contents: Vec<CharacterContents>,
    },
}

pub struct FootnoteElement {
    style: FootnoteElementStyle,
    contents: CharacterContents,
}

pub struct CrossRefElement {
    style: CrossRefElementStyle,
    contents: CharacterContents,
}

pub enum FootnoteElementStyle {
    TranslationQuote,
    AltTranslationQuote,
    Keyword,
    Label,
    Witness,
    Paragraph,
    Text,
    DeuteroText,
    Reference,
}

pub enum CrossRefElementStyle {
    Keyword,
    Quote,
    Target,
    ExtraTarget,
    Origin,
    OldTarget,
    NewTarget,
    DeuteroTarget,
    InlineQuote,
}

pub enum CharacterType {
    IntroOutline,
    IntroQuote,
    InlineQuote,

    Selah,
    AcrosticLetter,

    Addition,
    BookQuote,
    DeuteroAddition,
    Keyword,
    Deity,
    Ordinal,
    Proper,
    Geographic,
    ProperAddition,
    QuotedText,
    Signature,
    SecondaryText,
    Transliterated,
    Jesus,

    Emphasis,
    Bold,
    Italic,
    BoldItalic,
    Normal,
    SmallCap,
    Superscipt,

    Index,
    Ruby,
    Pronunciation,
    Word,
    GreekWord,
    HebrewWord,
    AramaicWord,
    Link,
}

pub enum FootnoteStyle {
    Footnote,
    Endnote,
}

pub enum ParagraphStyle {
    Normal,
    Margin,
    Opening,
    Right,
    Closure,
    EmbeddedOpening,
    Embedded,
    EmbeddedClosing,
    EmbeddedRefrain,
    Indented(u8),
    MarginIndented,
    Basic,
    Centered,
    HangingIndented(u8),
    Blank,
    LiturgicalNote,
}

pub enum PoetryStyle {
    Normal(u8),
    Right,
    Centered,
    AcrosticHeading,
    Embedded(u8),
    Descriptive,
    Blank,
}

pub enum ElementType {
    Remark,
    Header,
    Contents(u8),
    AltContents(u8),

    MajorIntro(u8),
    SectionIntro(u8),
    Intro,
    IndentedIntro,
    MarginIntro,
    MarginIndentedIntro,
    QuotedIntro,
    MarginQuotedIntro,
    RightIntro,
    PoetryIntro(u8),
    BlankIntro,
    ListIntro(u8),
    OutlineIntro,
    EntryIntro(u8),
    BridgeIntro,
    MajorTitleEndingIntro(u8),
    EndIntro,

    ChapterLabel,
    ChapterPublishedLabel,
    ChapterDescription,

    MajorTitle(u8),
    MajorTitleEnding(u8),
    MajorSection(u8),
    MajorReference,
    Section(u8),
    Reference,
    Parallel,
    // Inline,
    Descriptive,
    Speaker,
    Division(u8),
    PageBreak,
}

pub enum BookIdentifier {
    Genesis,
    Exodus,
    Leviticus,
    Numbers,
    Deuteronomy,
    Joshua,
    Judges,
    Ruth,
    OneSamuel,
    TwoSamuel,
    OneKings,
    TwoKings,
    OneChronicles,
    TwoChronicles,
    Ezra,
    Nehemiah,
    Esther,
    Job,
    Psalms,
    Proverbs,
    Ecclesiastes,
    SongOfSongs,
    Isaiah,
    Jeremiah,
    Lamentations,
    Ezekiel,
    Daniel,
    Hosea,
    Joel,
    Amos,
    Obadiah,
    Jonah,
    Micah,
    Nahum,
    Habakkuk,
    Zephaniah,
    Haggai,
    Zechariah,
    Malachi,
    Matthew,
    Mark,
    Luke,
    John,
    Acts,
    Romans,
    OneCorinthians,
    TwoCorinthians,
    Galatians,
    Ephesians,
    Philippians,
    Colossians,
    OneThessalonians,
    TwoThessalonians,
    OneTimothy,
    TwoTimothy,
    Titus,
    Philemon,
    Hebrews,
    James,
    OnePeter,
    TwoPeter,
    OneJohn,
    TwoJohn,
    ThreeJohn,
    Jude,
    Revelation,

    Tobit,
    Judith,
    EstherGreek,
    WisdomOfSolomon,
    Sirach,
    Baruch,
    LetterOfJeremiah,
    SongOfThreeYoungMen,
    Susanna,
    BelAndTheDragon,
    OneMaccabees,
    TwoMaccabees,
    ThreeMaccabees,
    FourMaccabees,
    OneEsdras,
    TwoEsdras,
    PrayerOfManasseh,
    Psalm151,
    Odes,
    PsalmsOfSolomon,

    EzraApocalypse,
    FiveEzra,
    SixEzra,
    DanielGreek,
    Psalms152To155,
    TwoBaruch,
    LetterOfBaruch,
    Jubilees,
    Enoch,
    OneMeqabyan,
    TwoMeqabyan,
    ThreeMeqabyan,
    Reproof,
    FourBaruch,
    LetterToLaodiceans,

    FrontMatter,
    BackMatter,
    OtherMatter,
    IntroductionMatter,
    Concordance,
    Glossary,
    TopicalIndex,
    NamesIndex,
    ExtraA,
    ExtraB,
    ExtraC,
    ExtraD,
    ExtraE,
    ExtraF,
    ExtraG,
}

pub enum BookEncoding {
    CP1252,
    CP1251,
    UTF8,
    UTF16,
}
